### ISSUE TITLE
unstable sensor message could lead rtabmap_ros DoS

### ISSUE THREAD

**Issue by GoesM** [introlab/rtabmap_ros#1138]
#### Environment
- Operating System:
  -  ubuntu22.04
- ROS2 Version:
  -  humble

#### Description
Considering the possibility of unstable sensor data transmission in the ROS (Robot Operating System) working network environment in real-world applications, it may be advisable to discard certain sensor information that is deemed unreasonable due to instability rather than interrupting operations, in order to prevent the occurrence of Denial of Service (DoS) phenomena.

**However**, I found if rtabmap_ros received such a scan-message (whose `range_max` is less than `range_min`), it would exit current work

the demo of scan-message:
```yaml
range_max: 0.5
range_min: 20.0
angle_increment: 0.0174930003
angle_max: 6.28000021
angle_min: 0
scan_time: 0
time_increment: 0
header:
  frame_id: base_scan
  stamp:
    nanosec: 395000000
    sec: 0
intensities:
- 0
- 0
- 0
- ...
ranges:
- 4.63112688
- 4.60988617
- 4.54179621
- ...
```

what happened to rtabmap_ros:
![image](https://github.com/introlab/rtabmap_ros/assets/130988564/2ec1168a-bf33-43d1-b66e-a8c7ed5b1eaa)

#### Suggestion

Can we opt to discard such blatantly erroneous messages instead of aborting the current task at hand? 

After all, the current mechanism makes it too easy for DoS incidents to occur.
