### ISSUE TITLE
stereo simulation in gazebo 

### ISSUE THREAD

**Issue by Dzksaigao** [introlab/rtabmap_ros#1241]
Hi,
I use libgazebo-ros-camera to create a stereo camera in gazebo and related topics can be subscribed in rviz2.
but rtabmap encounters error like this:
![截图 2024-11-23 15-12-02](https://github.com/user-attachments/assets/ad21f338-d98c-47d1-8ee9-6721cd7a7bf8)
this is the camera_info topic:
```
header:
  stamp:
    sec: 79
    nanosec: 33000000
  frame_id: camera_link
height: 240
width: 320
distortion_model: plumb_bob
d:
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
k:
- 277.19135641132203
- 0.0
- 160.5
- 0.0
- 277.19135641132203
- 120.5
- 0.0
- 0.0
- 1.0
r:
- 1.0
- 0.0
- 0.0
- 0.0
- 1.0
- 0.0
- 0.0
- 0.0
- 1.0
p:
- 277.19135641132203
- 0.0
- 160.5
- -19.403394948792545
- 0.0
- 277.19135641132203
- 120.5
- 0.0
- 0.0
- 0.0
- 1.0
- 0.0
binning_x: 0
binning_y: 0
roi:
  x_offset: 0
  y_offset: 0
  height: 0
  width: 0
  do_rectify: false
---
```
