### ISSUE TITLE
Sensor fusion with rtabmap

### ISSUE THREAD

**Issue by PhantatP** [introlab/rtabmap_ros#1307]
Right now, I've tried to fuse wheel odometry and rgbd_odometry from rtabmap together but it is always response as repeated data. How should I fix it?
This is my launch file
```xml
<launch>
    <arg name="rtabmap_args" default="" />
    <node pkg="tf" type="static_transform_publisher" name="map_to_odom"   args="0 0 0 0 0 0 map odom 100" />

    <group ns="rtabmap">
        <param name="robot_description" command="$(find xacro)/xacro $(find robotino_descrip)/urdf/robotino_real_copy.urdf" />
        <node name="joint_state_publisher" pkg="joint_state_publisher" type="joint_state_publisher"/>
        <node name="robot_state_publisher" pkg="robot_state_publisher" type="robot_state_publisher"/>
        <node name="rviz" pkg="rviz" type="rviz" args="-d $(find robotino_rtabmap)/rtabmap2.rviz"/>
        <node pkg="tf" type="static_transform_publisher" name="base_to_laser"  args="0 0 0.85 0 0 0 base_link laser 100" />
        <node pkg="tf" type="static_transform_publisher" name="base_to_camera" args="0 0 0.6 0 0 0 base_link camera_link 100" />
        <!--node pkg="tf" type="static_transform_publisher" name="odom_to_base" args="0 0 0 0 0 0 odom base_link 100" /-->

        <!-- RTAB-Map node -->
        <node name="rtabmap" pkg="rtabmap_slam" type="rtabmap" output="screen" args="">
            <param name="database_path" type="string" value="~/catkin_ws/maps/cage.db "/>
            <param name="frame_id" type="string" value="base_link"/>
            <param name="subscribe_rgbd" type="bool" value="false"/>
            <param name="subscribe_depth" type="bool" value="true"/>
            <param name="subscribe_laserScan" type="bool" value="true"/>
            <param name="use_action_for_goal" type="bool"   value="true"/>
            
            <!-- Remappings -->
            <remap from="odom" to="/odometry/filtered"/>
            <remap from="scan" to="/scan"/>
            <remap from="rgb/image" to="/camera/rgb/image_rect_color"/>
            <remap from="depth/image" to="/camera/depth_registered/image_raw"/>
            <remap from="rgb/camera_info" to="/camera/rgb/camera_info"/>
            <remap from="rgbd_image" to="/rgbd_camera/rgbd_image"/>
            
            <!-- Queue sizes -->
            <param name="sync_queue_size" type="int" value="300"/>
            <param name="topic_queue_size" type="int" value="300"/>
            
            <param name="Mem/IncrementalMemory" type="string" value="false"/>
            <param name="Mem/InitWMWithAllNodes" type="string" value="true"/>
            <param name="publish_tf_odom" value="false"/>

        </node>
    </group>
</launch>
```

and this is my ekf.yaml config
```yaml
frequency: 30
sensor_timeout: 0.5

odom0: /odom
odom0_config: [true, true, false,    # x, y, z
                         false, false, false,  # roll, pitch, yaw
                           true, true, false,    # vx, vy, vz
                          false, false, false,  # vroll, vpitch, vyaw
                           false, false, false]  # ax, ay, az
odom0_differential: true
odom0_relative: true
odom1: /odom_rgbd
odom1_config: [true, true, false,    # x, y, z
              false, false, false,   # roll, pitch, yaw
              true, true, false,     # vx, vy, vz
              false, false, true,    # vroll, vpitch, vyaw
              false, false, false]   # ax, ay, az

odom1_differential: false
odom1_relative: false
world_frame: odom
base_link_frame: base_link
odom_frame: odom
map_frame: map

two_d_mode: true
publish_tf: true
use_control: false
use_robot_localization_timestamp: false
```
