### ISSUE TITLE
Switching to mapping mode clears the existing map

### ISSUE THREAD

**Issue by mandrievich** [introlab/rtabmap_ros#1335]
Hello,

I encountered an issue when switching RTAB-Map from localization mode to mapping mode using the following setup:

``` yaml
frame_id: "base_link"
ground_truth_base_frame_id: "base_footprint"
odom_frame_id: "odom"
map_frame_id: "map"
subscribe_rgb: true
subscribe_depth: true
subscribe_odom_info: false
approx_sync: false
subscribe_rgbd: false
queue_size: 10
wait_for_transform_duration: 0.2
Mem/IncrementalMemory: "false"
Mem/InitWMWithAllNodes: "true"
RGBD/OptimizeFromGraphEnd: "false"
RGBD/LinearUpdate: "0.0"
RGBD/AngularUpdate: "0.0"
RGBD/ProximityBySpace: "false"
RGBD/ProximityPathMaxNeighbors: "0"
Reg/Force3DoF: "true"
Kp/DetectorStrategy: "6"
Vis/EstimationType: "0"
Vis/MinInliers: "15"
Optimizer/Strategy: "1"
Grid/3D: "false"
Grid/FlatObstacleDetected: "false"
Grid/MinClusterSize: "0"
Rtabmap/TimeThr: "0"
Rtabmap/DetectionRate: "3.5"
GridGlobal/Eroded: "false"
Grid/RayTracing: "false"
```
When I call the following service to switch to mapping mode:

``` bash
ros2 service call /rtabmap/set_mode_mapping std_srvs/srv/Empty "{}"
```

I expect that the previously built map will remain intact and that new data will be added to it — as described in this forum discussion:
http://official-rtab-map-forum.206.s1.nabble.com/Updating-map-when-doing-localization-in-3D-lidar-version-td8769.html

However, the existing map completely disappears, and I only see a small segment from the latest camera frame.

Could you please advise?
I'm using ROS 2 Jazzy.

Thank you in advance!
