### ISSUE TITLE
Baseline value 0.00

### ISSUE THREAD

**Issue by ankitvora7** [introlab/rtabmap_ros#404]
Hi,

Even though my values in the camera_info topic seem to be correct, I'm still getting a 0 baseline value. This is the error 
``` The stereo baseline (0.000000) should be positive (baseline=-Tx/fx). We assume a horizontal left/right stereo setup where the Tx (or P(0,3)) is negative in the right camera info msg.```

Here are my camera calibration values
```
header: 
  seq: 43821
  stamp: 
    secs: 4398
    nsecs: 200000000
  frame_id: "robot/left_camera/camera_info"
height: 480
width: 640
distortion_model: "plumb_bob"
D: [0.0, 0.0, 0.0, 0.0, 0.0]
K: [381.36246688113556, 0.0, 320.5, 0.0, 381.36246688113556, 240.5, 0.0, 0.0, 1.0]
R: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
P: [381.36246688113556, 0.0, 320.5, -157.29401728003162, 0.0, 381.36246688113556, 240.5, 0.0, 0.0, 0.0, 1.0, 0.0]
binning_x: 0
binning_y: 0
roi: 
  x_offset: 0
  y_offset: 0
  height: 0
  width: 0
  do_rectify: False
```
and the right camera is 

```
header: 
  seq: 44788
  stamp: 
    secs: 4494
    nsecs: 900000000
  frame_id: "robot/right_camera/camera_info"
height: 480
width: 640
distortion_model: "plumb_bob"
D: [0.0, 0.0, 0.0, 0.0, 0.0]
K: [381.36246688113556, 0.0, 320.5, 0.0, 381.36246688113556, 240.5, 0.0, 0.0, 1.0]
R: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
P: [381.36246688113556, 0.0, 320.5, -157.29401728003162, 0.0, 381.36246688113556, 240.5, 0.0, 0.0, 0.0, 1.0, 0.0]
binning_x: 0
binning_y: 0
roi: 
  x_offset: 0
  y_offset: 0
  height: 0
  width: 0
  do_rectify: False
```
The actual value should've been (-157.294/381.362) but it is 0.0. Any idea what might be going wrong ?
