### ISSUE TITLE
ROS2: ZED2 camera with RGB + Depth crashes rtabmap on startup

### ISSUE THREAD

**Issue by peredwardsson** [introlab/rtabmap_ros#651]
Jetson AGX Xavier
ROS2 Foxy via Docker based on [Dusty's Dockerfiles](https://github.com/dusty-nv/jetson-containers/blob/master/Dockerfile.ros.foxy)
Zed2 via PCI-E USB

To reproduce:
- Set `subscribe_rgb` and `subscribe_depth` true. Point to appropriate topics. Observe the following crash:
```
# ros2 launch hugo rtabmap.launch.py | grep rtabmap
[INFO] [rtabmap-17]: process started with pid [4829]
[rtabmap-17] 1632743874.265642726 [rtabmap] [INFO] rtabmap: subscribe_depth = true
[rtabmap-17] 1632743874.266235879 [rtabmap] [INFO] rtabmap: subscribe_rgb = true
[rtabmap-17] 1632743874.266321388 [rtabmap] [INFO] rtabmap: subscribe_stereo = false
[rtabmap-17] 1632743874.266370799 [rtabmap] [INFO] rtabmap: subscribe_rgbd = false (rgbd_cameras=1)
[rtabmap-17] 1632743874.266420850 [rtabmap] [INFO] rtabmap: subscribe_odom_info = false
[rtabmap-17] 1632743874.266467156 [rtabmap] [INFO] rtabmap: subscribe_user_data = false
[rtabmap-17] 1632743874.266539865 [rtabmap] [INFO] rtabmap: subscribe_scan = false
[rtabmap-17] 1632743874.266586267 [rtabmap] [INFO] rtabmap: subscribe_scan_cloud = false
[rtabmap-17] 1632743874.266632542 [rtabmap] [INFO] rtabmap: queue_size    = 10
[rtabmap-17] 1632743874.266679872 [rtabmap] [INFO] rtabmap: approx_sync   = false
[rtabmap-17] 1632743874.273861142 [rtabmap] [INFO] rtabmap(maps): map_filter_radius          = 0.000000
[rtabmap-17] 1632743874.273999134 [rtabmap] [INFO] rtabmap(maps): map_filter_angle           = 30.000000
[rtabmap-17] 1632743874.274065282 [rtabmap] [INFO] rtabmap(maps): map_cleanup                = true
[rtabmap-17] 1632743874.274126149 [rtabmap] [INFO] rtabmap(maps): map_always_update          = false
[rtabmap-17] 1632743874.274176936 [rtabmap] [INFO] rtabmap(maps): map_empty_ray_tracing      = true
[rtabmap-17] 1632743874.274229547 [rtabmap] [INFO] rtabmap(maps): cloud_output_voxelized     = true
[rtabmap-17] 1632743874.274280238 [rtabmap] [INFO] rtabmap(maps): cloud_subtract_filtering   = false
[rtabmap-17] 1632743874.274343249 [rtabmap] [INFO] rtabmap(maps): cloud_subtract_filtering_min_neighbors = 2
[rtabmap-17] 1632743874.341379963 [rtabmap] [INFO] rtabmap: frame_id      = base_link
[rtabmap-17] 1632743874.341533956 [rtabmap] [INFO] rtabmap: odom_frame_id = odom
[rtabmap-17] 1632743874.341591495 [rtabmap] [INFO] rtabmap: map_frame_id  = map
[rtabmap-17] 1632743874.341641578 [rtabmap] [INFO] rtabmap: use_action_for_goal  = false
[rtabmap-17] 1632743874.341701230 [rtabmap] [INFO] rtabmap: tf_delay      = 0.050000
[rtabmap-17] 1632743874.341762001 [rtabmap] [INFO] rtabmap: tf_tolerance  = 0.100000
[rtabmap-17] 1632743874.341814132 [rtabmap] [INFO] rtabmap: odom_sensor_sync   = false
[rtabmap-17] 1632743874.463858273 [rtabmap] [INFO] Setting RTAB-Map parameter "Grid/RangeMax"="10.0"
[rtabmap-17] 1632743874.467973321 [rtabmap] [INFO] Setting RTAB-Map parameter "Grid/RayTracing"="True"
[rtabmap-17] 1632743874.821971331 [rtabmap] [INFO] Update RTAB-Map parameter "Mem/IncrementalMemory"="false" from database
[rtabmap-17] 1632743875.186967337 [rtabmap] [INFO] RTAB-Map detection rate = 1.000000 Hz
[rtabmap-17] 1632743875.190368522 [rtabmap] [INFO] rtabmap: Using database from "/root/.ros/rtabmap.db" (965 MB).
[rtabmap-17] 1632743889.197649460 [rtabmap] [INFO] rtabmap: 2D occupancy grid map loaded (319x511).
[rtabmap-17] 1632743890.059005332 [rtabmap] [INFO] rtabmap: Database version = "0.20.13".
[rtabmap-17] 1632743890.132928387 [rtabmap] [INFO] Setup callbacks
[rtabmap-17] 1632743890.133119501 [rtabmap] [INFO] Setup depth callback
[rtabmap-17] 1632743890.165767009 [rtabmap] [INFO] 
[rtabmap-17] rtabmap subscribed to (exact sync):
[rtabmap-17]    /sensors/zed_front/rgb/image_rect_color,
[rtabmap-17]    /sensors/zed_front/depth/depth_registered,
[rtabmap-17]    rgb/camera_info
[rtabmap-17] terminate called after throwing an instance of 'UException'
[rtabmap-17]   what():  [FATAL] (2021-09-27 11:58:10.381) Transform.cpp:191::inverse() Condition (invertible) not met! [This transform is not invertible! xyz=[null] rpy=[null] 
[rtabmap-17] [0.000000 0.000000 0.000000 0.000000;
[rtabmap-17]  0.000000 0.000000 0.000000 0.000000;
[rtabmap-17]  0.000000 0.000000 0.000000 0.000000;
[rtabmap-17]  0 0 0 1]]
[ERROR] [rtabmap-17]: process has died [pid 4829, exit code -6, cmd '/opt/ros/foxy/install/lib/rtabmap_ros/rtabmap --ros-args -r __node:=rtabmap --params-file /tmp/launch_params_ovly2iry -r rgbd_image:=/sensors/rtabmap/rgbd -r depth/image:=/sensors/zed_front/depth/depth_registered -r rgb/camera_info:=/sensors/zed_front/rgb/camera_info -r rgb/image:=/sensors/zed_front/rgb/image_rect_color -r left/image_rect:=/sensors/zed_front/left/image_rect_color -r left/camera_info:=/sensors/zed_front/left/camera_info -r right/image_rect:=/sensors/zed_front/right/image_rect_color -r right/camera_info:=/sensors/zed_front/right/camera_info'].
```
(sidenote: rtabmap (and all nodelets I've tested so far) reports subscribing to the incorrect camera info topic. It actually subscribes to the correct one, but does not report the correct one)
- Crash also occurs when using the `rgbd_sync` nodelet to parse the data into an RGBD message. The nodelet works fine, but rtabmap crashes.
 
Echoing one such RGBD message (with no-arr) gives the following result:
```
---
header:
  stamp:
    sec: 1632743708
    nanosec: 332855704
  frame_id: ''
rgb_camera_info:
  header:
    stamp:
      sec: 1632743708
      nanosec: 332855704
    frame_id: ''
  height: 360
  width: 640
  distortion_model: plumb_bob
  d: '<sequence type: double, length: 5>'
  k: '<array type: double[9]>'
  r: '<array type: double[9]>'
  p: '<array type: double[12]>'
  binning_x: 0
  binning_y: 0
  roi:
    x_offset: 0
    y_offset: 0
    height: 0
    width: 0
    do_rectify: false
depth_camera_info:
  header:
    stamp:
      sec: 1632743708
      nanosec: 332855704
    frame_id: ''
  height: 360
  width: 640
  distortion_model: plumb_bob
  d: '<sequence type: double, length: 5>'
  k: '<array type: double[9]>'
  r: '<array type: double[9]>'
  p: '<array type: double[12]>'
  binning_x: 0
  binning_y: 0
  roi:
    x_offset: 0
    y_offset: 0
    height: 0
    width: 0
    do_rectify: false
rgb:
  header:
    stamp:
      sec: 1632743708
      nanosec: 332855704
    frame_id: zed2_front_left_camera_optical_frame
  height: 360
  width: 640
  encoding: bgra8
  is_bigendian: 0
  step: 2560
  data: '<sequence type: uint8, length: 921600>'
depth:
  header:
    stamp:
      sec: 1632743708
      nanosec: 332855704
    frame_id: zed2_front_left_camera_optical_frame
  height: 72
  width: 128
  encoding: 32FC1
  is_bigendian: 0
  step: 512
  data: '<sequence type: uint8, length: 36864>'
rgb_compressed:
  header:
    stamp:
      sec: 0
      nanosec: 0
    frame_id: ''
  format: ''
  data: '<sequence type: uint8, length: 0>'
depth_compressed:
  header:
    stamp:
      sec: 0
      nanosec: 0
    frame_id: ''
  format: ''
  data: '<sequence type: uint8, length: 0>'
---
```

I am unable to use multiple cameras as input due to this issue.
