### ISSUE TITLE
transformation error

### ISSUE THREAD

**Issue by Annaiyan** [introlab/rtabmap_ros#93]
I'm trying to make octomap with stereo camera.I have launched like this,

**>  ROS_NAMESPACE=/stereo_camera rosrun ueye stereo
which will publish 

> /stereo_camera/camera/parameter_descriptions
> /stereo_camera/camera/parameter_updates
> /stereo_camera/left/camera_info
> /stereo_camera/left/image_raw
> /stereo_camera/right/camera_info
> /stereo_camera/right/image_raw
> after i have launched the demo_stereo_outdoor.launch file with some modification like below,
> 
> ```
> <launch>  
> ```

   
   <arg name="rviz" default="true" />
   <arg name="rtabmapviz" default="false" />

   <param name="use_sim_time" type="bool" value="false"/>   

   
   <group ns="/stereo_camera" >
      <node pkg="nodelet" type="nodelet" name="stereo_nodelet"  args="manager"/>

```
  <node pkg="stereo_image_proc" type="stereo_image_proc" name="stereo_image_proc">

  </node>
```

   </group>

   <group ns="rtabmap">   

```
  <!-- Stereo Odometry -->   
  <node pkg="rtabmap_ros" type="stereo_odometry" name="stereo_odometry" output="screen">
     <remap from="left/image_rect"       to="/stereo_camera/left/image_rect"/>
     <remap from="right/image_rect"      to="/stereo_camera/right/image_rect"/>
     <remap from="left/camera_info"      to="/stereo_camera/left/camera_info"/>
     <remap from="right/camera_info"     to="/stereo_camera/right/camera_info"/>
     <remap from="odom"                  to="/stereo_odometry"/>

     <param name="frame_id"      type="string" value="base_footprint"/>
     <param name="odom_frame_id" type="string" value="odom"/>

     <param name="Odom/Strategy"      type="string" value="0"/> <!-- 0=Frame-to-Map, 1=Frame=to=Frame -->
     <param name="Vis/EstimationType" type="string" value="0"/> <!-- 0=3D->3D 1=3D->2D (PnP) -->
     <param name="Vis/MaxDepth"       type="string" value="10"/>
     <param name="Vis/MinInliers"     type="string" value="10"/>
     <param name="Odom/FillInfoData"  type="string" value="$(arg rtabmapviz)"/> 
     <param name="GFTT/MinDistance"   type="string" value="10"/>
     <param name="GFTT/QualityLevel"  type="string" value="0.00001"/> 
  </node>

  <!-- Visual SLAM: args: "delete_db_on_start" and "udebug" -->
  <node name="rtabmap" pkg="rtabmap_ros" type="rtabmap" output="screen" args="--delete_db_on_start">
     <param name="frame_id"         type="string" value="base_footprint"/>
     <param name="subscribe_stereo" type="bool" value="true"/>
     <param name="subscribe_depth"  type="bool" value="false"/>

     <remap from="left/image_rect"   to="/stereo_camera/left/image_rect_color"/>
     <remap from="right/image_rect"  to="/stereo_camera/right/image_rect"/>
     <remap from="left/camera_info"  to="/stereo_camera/left/camera_info"/>
     <remap from="right/camera_info" to="/stereo_camera/right/camera_info"/>

     <remap from="odom" to="/stereo_odometry"/>

     <param name="queue_size" type="int" value="30"/>

     <!-- RTAB-Map's parameters -->
     <param name="Rtabmap/TimeThr"                   type="string" value="700"/>
     <param name="Kp/MaxFeatures"                    type="string" value="200"/>
     <param name="Kp/MaxDepth"                       type="string" value="10"/>
     <param name="Kp/DetectorStrategy"               type="string" value="0"/>   <!-- use SURF -->
     <param name="SURF/HessianThreshold"             type="string" value="1000"/>
     <param name="Vis/EstimationType"                type="string" value="0"/>   <!-- 0=3D->3D, 1=3D->2D (PnP) -->
     <param name="RGBD/LoopClosureReextractFeatures" type="string" value="true"/>
     <param name="Vis/MaxDepth"                      type="string" value="10"/>
  </node>

  <node if="$(arg rtabmapviz)" pkg="rtabmap_ros" type="rtabmapviz" name="rtabmapviz" args="-d $(find rtabmap_ros)/launch/config/rgbd_gui.ini" output="screen">
     <param name="subscribe_stereo"    type="bool" value="true"/>
     <param name="subscribe_odom_info" type="bool" value="true"/>
     <param name="queue_size"          type="int" value="10"/>
     <param name="frame_id"            type="string" value="base_footprint"/>

     <remap from="left/image_rect"  to="/stereo_camera/left/image_rect_color"/>
     <remap from="right/image_rect"  to="/stereo_camera/right/image_rect"/>
     <remap from="left/camera_info"  to="/stereo_camera/left/camera_info"/>
     <remap from="right/camera_info" to="/stereo_camera/right/camera_info"/>
     <remap from="odom_info"         to="odom_info"/>
     <remap from="odom"              to="/stereo_odometry"/>
     <remap from="mapData"           to="mapData"/>
  </node>
```

   </group>

   <node if="$(arg rviz)" pkg="rviz" type="rviz" name="rviz" args="-d $(find rtabmap_ros)/launch/config/demo_stereo_outdoor.rviz"/>

</launch>

```



also i do the transformation from camera frame id which is /left using rosrun tf static_publisher 0 0 0 0 0 0 base_footprint left 100.
But the transformation doesn't work.I'm getting the following error
```

> odometry: Could not get transform from base_footprint to /left (stamp=1467028492.328837) after 0.100000 seconds ("wait_for_transform_duration"=0.100000)!
> The stereo baseline (-0.223329) should be positive (baseline=-Tx/fx). We assume a horizontal left/right stereo setup where the Tx (or P(0,3)) is negative in the right camera info msg.
> I have executed the tutorial with rosbag,it works fine (i can see the octomap if i launch octomap_server_node).
> 
> ```
> ```

why the transformation is not working?
Am i missing anything in the launch file?

Thanks in advance,

-Arun

**Comment by matlabbe** [comment]
Hi,

It looks like that published images by `ueye stereo` are not synchronized, the [left and right images have different timestamps](https://bitbucket.org/kmhallen/ueye/src/91d7a3ce87fc594e2be02ccfc168145b21172c15/src/StereoNode.cpp?at=default&fileviewer=file-view-default#StereoNode.cpp-475:505). You should set `approx_sync` to `true` for `stereo_odometry` node and `stereo_approx_sync` to `true` for `rtabmap` node.

The message:
<raw>
The stereo baseline (-0.223329) should be positive (baseline=-Tx/fx). We assume a horizontal left/right stereo setup where the Tx (or P(0,3)) is negative in the right camera info msg.
</raw>
tells that there is a problem with the calibration. Did you use this [tutorial](http://wiki.ros.org/camera_calibration/Tutorials/StereoCalibration) to calibrate the cameras?

cheers

**Comment by Annaiyan** [comment]
I have added the approx_sync and stereo_approx_sync.

> <param name="approx_sync"           type="bool"   value="true"/>
> <param name="stereo_approx_sync"   type="bool"   value="true"/>

Usually i calibrate using the ros tutorial ( as mentioned above).Using the stereo_image_proc node i can get the 3D point cloud without problem.
is there any other option?

**Comment by matlabbe** [comment]
Can you show your camera info values for the left and right images?
```
$ rostopic echo /stereo_camera/left/camera_info
$ rostopic echo /stereo_camera/right/camera_info
```

Another approach to use stereo cameras is to generate a depth image from the disparity image using [disparity_to_depth](http://wiki.ros.org/rtabmap_ros#rtabmap_ros.2BAC8-disparity_to_depth) nodelet, then uses the RGB-D interface instead of the stereo one.

cheers

**Comment by Annaiyan** [comment]
here it is
/stereo_camera/left/camera_info
```
header: 
  seq: 474833
  stamp: 
    secs: 1467043998
    nsecs: 230242079
  frame_id: /left
height: 480
width: 752
distortion_model: plumb_bob
D: [0.05017381750693655, -0.08624079495140854, 0.0003068409695639882, 0.000677080628844562, 0.0]
K: [552.3732902673913, 0.0, 363.51933244136427, 0.0, 552.8141476458964, 219.7955026697695, 0.0, 0.0, 1.0]
R: [0.9999220342320602, -0.009443783893361217, -0.008169479970851845, 0.009284006356935394, 0.9997690937204566, -0.019379537335577894, 0.008350609749176471, 0.01930218089108497, 0.9997788221050019]
P: [581.5208662261348, 0.0, 365.81403732299805, 0.0, 0.0, 581.5208662261348, 239.09959602355957, 0.0, 0.0, 0.0, 1.0, 0.0]
binning_x: 0
binning_y: 0
roi: 
  x_offset: 0
  y_offset: 0
  height: 0
  width: 0
  do_rectify: False
``
/stereo_camera/right/camera_info
header: 
  seq: 474426
  stamp: 
    secs: 1467043998
    nsecs: 230242079
  frame_id: /left
height: 480
width: 752
distortion_model: plumb_bob
D: [0.027953063640482917, -0.05402691085378825, 0.0011373858995405864, -0.000966441379761347, 0.0]
K: [550.918504266175, 0.0, 360.00669342670585, 0.0, 551.7017610593424, 257.6691044303571, 0.0, 0.0, 1.0]
R: [0.9999733547444588, 0.006297571443670056, -0.003691936487088545, -0.00622498631824261, 0.999793336895366, 0.019352856248285973, 0.0038130494948946446, -0.01932935833236583, 0.9998058994424911]
P: [581.5208662261348, 0.0, 365.81403732299805, 129.71830781337002, 0.0, 581.5208662261348, 239.09959602355957, 0.0, 0.0, 0.0, 1.0, 0.0]
binning_x: 0
binning_y: 0
roi: 
  x_offset: 0
  y_offset: 0
  height: 0
  width: 0
  do_rectify: False

```
