### ISSUE TITLE
What is the localization priority between proximity detection and landmark detection?

### ISSUE THREAD

**Issue by wizard-coder** [introlab/rtabmap_ros#931]
Hi
we have a problem with localization with landmark detection.

we am using rtabmap to navigate through the tunnel.

For localization, we are using only 3d lidar(velodyne 16), and for landmark detection, we are using apriltag ros.

If the RGBD/ProximityPathMaxNeighbors parameter is set to 0(i.e. proximity detection is disabled), localization is performed by landmark detection.

But, When RGBD/ProximityPathMaxNeighbors parameter is set to 1, localization is not triggered by landmark detection, even though april tag is detected (Loop/Landmark_detected value is changed in rtabmap/info topic).

Is there a priority between proximity detection and landmark detection?

Below is the rtabmap setting.

```yaml
Rtabmap/DetectionRate: 1

RGBD/NeighborLinkRefining: false
RGBD/ProximityBySpace: true
RGBD/ProximityMaxGraphDepth: 50
RGBD/ProximityPathMaxNeighbors: 1
RGBD/AngularUpdate: 0.05
RGBD/LinearUpdate: 0.05
RGBD/MaxLoopClosureDistance: 0
RGBD/MarkerDetection: false
RGBD/ProximityPathFilteringRadius: 3

Marker/Dictionary: 20
Marker/Length: 0.1
Marker/CornerRefinementMethod: 3
Marker/VarianceLinear: 0.1
Marker/VarianceAngular: 9999

Mem/NotLinkedNodesKept: false
Mem/STMSize: 30
Mem/LaserScanNormalK: 20

Reg/Strategy: 1
Reg/Force3DoF: true

Kp/MaxFeatures: -1

Optimizer/GravitySigma: 0.3
Optimizer/Iterations: 20

Grid/Sensor: 0 
Grid/3D: false
GridGlobal/ProbHit: 0.9 
GridGlobal/ProbMiss: 0.35 
Grid/RayTracing: true
Grid/RangeMax: 10.0
Grid/RangeMin: 1.0
Grid/MaxObstacleHeight: 0.0 
Grid/MaxGroundHeight: 0.2
Grid/NormalsSegmentation: true

Icp/VoxelSize: 0.05
Icp/PointToPlaneK: 20
Icp/PointToPlaneRadius: 0
Icp/PointToPlane: true
Icp/Iterations: 30
Icp/Epsilon: 0.1
Icp/MaxTranslation: 10.0 
Icp/MaxRotation: 3.14 
Icp/MaxCorrespondenceDistance: 0.5 
Icp/Strategy: 1
Icp/OutlierRatio: 0.85 
Icp/CorrespondenceRatio: 0.1
Icp/Force4DoF: true
Icp/DownsamplingStep: 1
Icp/RangeMin: 1
Icp/RangeMax: 10
Icp/PointToPlaneLowComplexityStrategy: 2

Mem/IncrementalMemory: false
```
