### ISSUE TITLE
Jittery position when stationary

### ISSUE THREAD

**Issue by peredwardsson** [introlab/rtabmap_ros#945]
The `map -> odom` transform looks a little nervous when stationary. The environment is a little pale so I understand the positioning not being exact in this case, but here, you can clearly see from the odometry that we are not moving. Is it possible to factor this into the `map -> odom` transform corrections? It jumps around 40 cm in one direction only, when the input (in my case, two rgbd cameras) look at the same targets. I think the depth camera might be shifting, which could cause the corrections to trigger, but it is absolutely stationary, just like the odometry is suggesting.
<img width="550" alt="Screenshot 2023-04-13 at 15 39 46" src="https://user-images.githubusercontent.com/15907557/231776884-f659bdba-67b6-4d52-aaa9-53ad0d1a7a0b.png">

Here are my params for Rtabmap:
```
/**:
  # rtabmap:
  ros__parameters:
    subscribe_depth: False
    subscribe_rgb: False
    subscribe_stereo: false
    subscribe_scan: False
    subscribe_rgbd: True
    approx_sync: True
    odom_frame_id: "odom"
    map_always_update: False
    map_empty_ray_tracing: True
    rgbd_cameras: 2
    publish_tf: True

    Grid/RayTracing: "True"
    Grid/RangeMax: "8.0"
    Grid/CellSize: "0.1"
    Grid/NoiseFilteringRadius: "0.1"
    Grid/NoiseFilteringMinNeighbors: "6"
    Grid/NormalK: "20"
    Grid/DepthDecimation: "1"
    GridGlobal/Eroded: "True"
    GridGlobal/FootprintRadius: "0.6"

    RGBD/AngularUpdate: "0.1"
    RGBD/LinearUpdate: "0.1"
    RGBD/OptimizeFromGraphEnd: "False"
    RGBD/NeighborLinkRefining: "True"
    RGBD/MarkerDetection: "True"
    RGBD/ProximityBySpace: "True"
    RGBD/ProximityPathMaxNeighbors: "10"
    RGBD/ProximityPathFilteringRadius: "1.5"

    Reg/Strategy: "0"
    Reg/Force3DoF: "True"

    Mem/ReduceGraph: "True"
    Mem/NotLinkedNodesKept: "False"
    Mem/BinDataKept: "False"
    Mem/STMSize: "30"

    Kp/MaxFeatures: "200"
    Vis/CorFlowMaxLevel: "5"
    Vis/EstimationType: "0" # should be 0 for multi-camera input
    Vis/CorGuessWinSize: "0" # should be 0 for multi-camera input
    OdomF2M/BundleAdjustment: "0" # should be 0 for mult-camera input
    SURF/GpuVersion: "True"
```
